name = "OmopTestData"
uuid = "749aaa6d-cbed-4cd9-b519-9c6daacb4162"
authors = ["AshlinHarris <90787010+AshlinHarris@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
